from dotenv import load_dotenv
import os

load_dotenv(override=True)

ASTRA_DB_API_ENDPOINT = os.environ.get("ASTRA_DB_API_ENDPOINT")
ASTRA_DB_APPLICATION_TOKEN = os.environ.get("ASTRA_DB_APPLICATION_TOKEN")
POSTGRES_USERNAME = os.environ.get("POSTGRES_USER")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
POSTGRES_DB = os.environ.get("POSTGRES_DB")
POSTGRES_ITEMS_TABLE_NAME = os.environ.get("ITEMS_TABLE_NAME")
POSTGRES_INTERACTIONS_TABLE_NAME = os.environ.get("INTERACTIONS_TABLE_NAME")
ASTRA_DB_VSTORE_ITEMS_COLLECTION_NAME = os.environ.get(
    "ASTRA_DB_VSTORE_ITEMS_COLLECTION_NAME")
ASTRA_DB_VSTORE_USER_PROFILES_COLLECTION_NAME = os.environ.get(
    "ASTRA_DB_VSTORE_USER_PROFILES_COLLECTION_NAME")
POSTGRES_PRIMARY_KEY_NAME = os.environ.get("PRIMARY_KEY_NAME")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT")
